In [3]:
import numpy as np

X_1= [4,3,4,4,3,3,3,3,4,4,4,5,4,3,4]
X_2 = [3028,1365,2726,2538,1318,1693,1412,1632,2875,3564,4412,4444,4278,3064,3857]

X_1_train = (X_1 - np.mean(X_1)) / np.std(X_1)
X_2_train = (X_2 - np.mean(X_2)) / np.std(X_2)

print(X_1)
print(X_2)

[4, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4, 5, 4, 3, 4]
[3028, 1365, 2726, 2538, 1318, 1693, 1412, 1632, 2875, 3564, 4412, 4444, 4278, 3064, 3857]


Modify for 'N' number of features 

In [4]:
C = np.array([[np.dot(X_1_train, X_2_train), np.dot(X_1_train, X_2_train)], [np.dot(X_2_train, X_1_train), np.dot(X_2_train, X_2_train)]]) / (15 - 1)
print(C)

[[0.87414684 0.87414684]
 [0.87414684 1.07142857]]


In [9]:
X_1_test = [1,4,3,3]
X_2_test = [2000,4278,3064,3857]

X_1_test = (X_1_test - np.mean(X_1)) / np.std(X_1)
X_2_test = (X_2_test - np.mean(X_2)) / np.std(X_2)

print(X_1_test)
print(X_2_test)

[-4.47213595  0.55901699 -1.11803399 -1.11803399]
[-0.73961352  1.33089229  0.22747085  0.94823955]


In [12]:
proximity_measure = []

for i in range(len(X_1_test)) :
    Z = X_1_test[i]**2 + X_2_test[i]**2 + np.dot(np.dot([X_1_test[i], X_2_test[i]], C), [[X_1_test[i]], [X_2_test[i]]])
    proximity_measure.append(Z[0])

print(proximity_measure)

[44.39881399563443, 5.555454554366418, 2.0052391594509515, 2.351747528494332]
