In [2]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

X_1= [4,3,4,4,3,3,3,3,4,4,4,5,4,3,4]
X_2 = [3028,1365,2726,2538,1318,1693,1412,1632,2875,3564,4412,4444,4278,3064,3857]

x_train = [(x, y) for x, y in zip(X_1, X_2)]
x_train = np.array(x_train)
X_train = StandardScaler().fit_transform(x_train) # Fit into a standard distribution

# feature_1 = X[:, 0]

In [3]:
pca = PCA()
X_pca = pca.fit_transform(X_train)

M = pca.components_ # What is this?

print(M)

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [4]:
C = np.cov(X_train, rowvar=False)

print(C)

[[1.07142857 0.87414684]
 [0.87414684 1.07142857]]


In [8]:
scaler = StandardScaler().fit(x_train)

X_1_test = [1,4,3,3] # Input feature_1
X_2_test = [2000,4278,3064,3857] # Input feature_2

x_test = [(x, y) for x, y in zip(X_1_test, X_2_test)]
x_test = np.array(x_test)

X_test = scaler.transform(x_test)

print(X_test)

[[-4.47213595 -0.73961352]
 [ 0.55901699  1.33089229]
 [-1.11803399  0.22747085]
 [-1.11803399  0.94823955]]


Implement proximity measure function for N-feature linear PCA

In [9]:
proximity_measure = []

for i in range(len(X_1_test)) :
    Z = X_1_test[i]**2 + X_2_test[i]**2 + np.dot(np.dot([X_1_test[i], X_2_test[i]], C), [[X_1_test[i]], [X_2_test[i]]])
    proximity_measure.append(Z[0])

print(proximity_measure)

[8289212.9445, 37939752.51571344, 19462859.24406486, 30835749.6490119]
