<h1>Linear PCA for Classical Anomaly Detection</h1>
Based on a research paper from:
<br>
Datset used:
<br>
Adding the dataset to the notebook


In [6]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('Dataset\Kaggle\Production Quality\data_X.csv')

x = df.iloc[:, 1:18].values
x = np.array(x)

X = StandardScaler().fit_transform(x)

print(x)
print(X)

[[212.   210.   211.   ... 243.   167.85   9.22]
 [212.   211.   211.   ... 243.   162.51   9.22]
 [212.   211.   211.   ... 242.   164.99   9.22]
 ...
 [271.   261.   265.   ... 280.   160.14   8.44]
 [271.   261.   265.   ... 280.   162.96   8.44]
 [271.   261.   265.   ... 280.   159.73   7.35]]
[[-1.18886122 -1.3006378  -1.27898295 ... -0.21770786 -0.47568099
   1.49877297]
 [-1.18886122 -1.26819607 -1.27898295 ... -0.21770786 -0.84558629
   1.49877297]
 [-1.18886122 -1.26819607 -1.27898295 ... -0.25023212 -0.67379506
   1.49877297]
 ...
 [ 0.64819495  0.3538901   0.48047645 ...  0.98568958 -1.00975775
   0.81934596]
 [ 0.64819495  0.3538901   0.48047645 ...  0.98568958 -0.8144145
   0.81934596]
 [ 0.64819495  0.3538901   0.48047645 ...  0.98568958 -1.03815872
  -0.13010972]]


Splitting the dataset into training and testing variables

In [2]:
# Split the dataset into training and testing variables

Building a PCA object using the Sklearn python library

In [3]:
pca = PCA(n_components = 16)
X_pca = pca.fit_transform(X)

M = pca.components_

print(M)

[[ 4.29737274e-01  4.41220675e-01  4.44595160e-01 -7.05682562e-03
  -1.17729962e-02 -1.19127729e-02 -4.31780436e-02 -4.95139216e-02
  -4.24205145e-02  8.61775456e-03  9.26987019e-03  8.07541415e-03
  -3.69455385e-01 -3.70706662e-01 -3.76462380e-01 -2.58543954e-02
  -1.02652548e-03]
 [ 3.74630308e-01  3.75138312e-01  3.67246339e-01  1.31783964e-02
   2.32930674e-02  2.38296454e-02 -1.35500170e-02 -1.38771476e-02
  -2.14981455e-02 -2.95254537e-02 -3.74081449e-02 -2.67320265e-02
   4.40642838e-01  4.41976534e-01  4.35216415e-01  9.26369894e-04
  -4.66813709e-03]
 [ 4.17731841e-02  4.23078567e-02  4.30149199e-02 -5.68439992e-02
  -5.58347978e-02 -4.68050199e-02  5.64620097e-01  5.62569645e-01
   5.66570553e-01 -9.39494926e-02 -1.01197207e-01 -9.69471086e-02
  -2.25329065e-02 -1.65638798e-02 -1.93934208e-02  1.27111933e-02
  -2.59610108e-03]
 [-8.87247078e-03 -1.56475186e-02 -2.29426867e-02 -3.52320847e-01
  -3.43147227e-01 -3.59677014e-01 -1.05462253e-01 -1.06623712e-01
  -1.14050128e-01 -

Determining the covariance matrix

In [7]:
C = np.cov(X, rowvar=False)

print(C)

[[ 1.00000048e+00  6.62834844e-01  6.56003985e-01 -7.72256215e-03
  -3.84689585e-03 -4.42890274e-03 -8.78130603e-03 -8.44408447e-03
  -8.11932558e-03 -3.79503475e-03 -1.21304656e-02 -5.35411822e-03
  -4.36425525e-03 -7.21672102e-04 -1.29939729e-02 -1.76677916e-02
  -2.48103199e-03]
 [ 6.62834844e-01  1.00000048e+00  6.87811435e-01  5.66802461e-03
   4.72593213e-03  5.36990604e-03 -8.00666359e-04 -1.33558954e-02
  -1.05180795e-02 -7.15868182e-03 -1.39250036e-02 -4.00241750e-03
  -1.17354126e-02 -1.19527296e-02 -2.04148888e-02 -1.64252392e-02
  -2.20764219e-03]
 [ 6.56003985e-01  6.87811435e-01  1.00000048e+00 -1.54811295e-03
   3.04376260e-03  6.04547737e-03 -3.01905491e-03 -8.17017699e-03
  -7.32696904e-03  1.29672275e-03  1.52994520e-03  2.70679449e-03
  -1.85833131e-02 -2.13708465e-02 -3.10549388e-02 -1.03678126e-02
  -3.85826954e-03]
 [-7.72256215e-03  5.66802461e-03 -1.54811295e-03  1.00000048e+00
   3.76902104e-01  4.06272466e-01 -1.04520635e-02 -9.80708486e-03
  -8.50368891e-03  

Pre-processing the test data to work with the PCA model built

In [ ]:
scaler = StandardScaler().fit(x)

x_test # Testing data

X_test = scaler.transform(x_test)

Configuring the code to work with new data

In [ ]:
# Modify the code to accomodate new data